spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: {your google Id}
    password: {App Password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true